version: '3.8'

networks:
  tech-challenger-net:
    driver: bridge

services:
  tc-app:
    image: ${APP_NAME}:1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${APP_PORT}
    container_name: ${APP_NAME}
    networks:
      - tech-challenger-net
    environment:
      MYSQL_HOST: "mysql-db"

    depends_on:
      - mysql-db
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    command: bash -c "./config/init_db/init_db.sh && poetry run uvicorn src.app:app --host 0.0.0.0 --port ${APP_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql-db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    networks:
      - tech-challenger-net
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  mysql-data:
