apiVersion: v1
kind: Service
metadata:
  name: supply-microservice-db-service
spec:
  selector:
    app: supply-microservice-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30002
  type: NodePort
