apiVersion: v1
kind: Service
metadata:
  name: supply-microservice-svc
  labels:
    app: supply-microservice-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8003
      nodePort: 32000
  selector:
    app: supply-microservice-pod