apiVersion: apps/v1
kind: Deployment
metadata:
  name: supply-microservice-pod
  labels:
    app: supply-microservice-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supply-microservice-pod
  template:
    metadata:
      labels:
        app: supply-microservice-pod
    spec:
      containers:
      - name: supply-microservice-app
        image: 414132512745.dkr.ecr.us-east-1.amazonaws.com/soattc:latest
        ports:
        - containerPort: 8003
        resources:
          requests:
            cpu: 25m
          limits:
            cpu: 100m
        envFrom:
          - configMapRef:
              name: tc-app-config
          - secretRef:
              name: application-secrets
          - secretRef:
              name: mysql-secrets
          - secretRef:
              name: mercadopago-secrets
          - secretRef:
              name: webhook-secrets